---
- name: Deploy Nginx Web App
  hosts: localhost
  become: true
  tasks:
    - name: Log in to Azure Container Registry
      ansible.builtin.command:
        cmd: docker login ***.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} -p ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Pull Docker image from Azure Container Registry
      ansible.builtin.command:
        cmd: docker pull ***.azurecr.io/myapp:v1

    - name: Run Docker container
      ansible.builtin.command:
        cmd: docker run -d -p 80:80 ***.azurecr.io/myapp:v1
