---
- name: Deploy Nginx Web App
  hosts: localhost
  become: true

  tasks:
    - name: Log in to Azure
      ansible.builtin.command:
        cmd: az login --service-principal -u "{{ lookup('env', 'AZURE_CLIENT_ID') }}" -p "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}" --tenant "{{ lookup('env', 'AZURE_TENANT_ID') }}"

    - name: Log in to Azure Container Registry
      ansible.builtin.command:
        cmd: docker login devopsregistry2025.azurecr.io -u "{{ lookup('env', 'ACR_USERNAME') }}" -p "{{ lookup('env', 'ACR_PASSWORD') }}"

    - name: Pull Docker image from ACR
      ansible.builtin.command:
        cmd: docker pull devopsregistry2025.azurecr.io/myapp:v1

    - name: Install kubectl
      ansible.builtin.shell: |
        sudo apt-get update -y
        sudo apt-get install -y kubectl

    - name: Get AKS credentials
      ansible.builtin.command:
        cmd: az aks get-credentials --resource-group devops-rg --name devops-aks --overwrite-existing

    - name: Deploy to AKS
      ansible.builtin.command:
        cmd: kubectl apply -f ./app/kubernetes/
