---
- name: Deploy Nginx Web App
  hosts: localhost
  become: true

  tasks:
    - name: Log in to Azure Container Registry
      ansible.builtin.command:
        cmd: docker login devopsregistry2025.azurecr.io -u "{{ lookup('env', 'ACR_USERNAME') }}" -p "{{ lookup('env', 'ACR_PASSWORD') }}"

    - name: Pull Docker image from Azure Container Registry
      ansible.builtin.command:
        cmd: docker pull devopsregistry2025.azurecr.io/myapp:v1

    - name: Run Docker container
      ansible.builtin.command:
        cmd: docker run -d -p 80:80 devopsregistry2025.azurecr.io/myapp:v1
