name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: devopsregistry2025.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t devopsregistry2025.azurecr.io/myapp:v1 .
          docker push devopsregistry2025.azurecr.io/myapp:v1

      - name: Run Ansible Playbook
        run: |
          sudo apt-get update
          sudo apt-get install ansible -y
          ansible-playbook ansible/deploy.yml
